<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>GoPro.Common</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWPF>True</UseWPF>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="controls/checkbox.baml" />
    <None Remove="controls/sliderperformance.baml" />
    <None Remove="dialogs/autoupdatewindow.baml" />
    <None Remove="controls/numerictextbox.baml" />
    <None Remove="controls/resolutiontextbox.baml" />
    <None Remove="controls/scrubber.baml" />
    <None Remove="controls/combobox.baml" />
    <None Remove="dialogs/progresswindow.baml" />
    <None Remove="dialogs/messagewindow.baml" />
    <None Remove="controls/icons.baml" />
    <None Remove="controls/radiobutton.baml" />
    <None Remove="controls/controls.baml" />
    <None Remove="controls/numericupdown.baml" />
    <EmbeddedResource Include="controls/checkbox.baml" />
    <EmbeddedResource Include="controls/sliderperformance.baml" />
    <EmbeddedResource Include="dialogs/autoupdatewindow.baml" />
    <EmbeddedResource Include="controls/numerictextbox.baml" />
    <EmbeddedResource Include="controls/resolutiontextbox.baml" />
    <EmbeddedResource Include="controls/scrubber.baml" />
    <EmbeddedResource Include="controls/combobox.baml" />
    <EmbeddedResource Include="dialogs/progresswindow.baml" />
    <EmbeddedResource Include="dialogs/messagewindow.baml" />
    <EmbeddedResource Include="controls/icons.baml" />
    <EmbeddedResource Include="controls/radiobutton.baml" />
    <EmbeddedResource Include="controls/controls.baml" />
    <EmbeddedResource Include="controls/numericupdown.baml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WindowsBase">
      <HintPath>../../artifacts/linux-x64/WindowsBase.dll</HintPath>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="System.Management" />
    <Reference Include="System.Net.Http" />
    <Reference Include="GoPro.Core">
      <HintPath>../../Player.App/GoPro.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../artifacts/linux-x64/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Windows.Services.Store.StoreContract" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>../../Player.App/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Windows.Foundation.UniversalApiContract" />
    <Reference Include="Microsoft.AppCenter.Crashes">
      <HintPath>../../Player.App/Microsoft.AppCenter.Crashes.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AppCenter.Analytics">
      <HintPath>../../Player.App/Microsoft.AppCenter.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AppCenter">
      <HintPath>../../Player.App/Microsoft.AppCenter.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <HintPath>../../artifacts/linux-x64/Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression.FileSystem">
      <HintPath>../../artifacts/linux-x64/System.IO.Compression.FileSystem.dll</HintPath>
    </Reference>
    <Reference Include="Windows.Foundation.FoundationContract" />
    <Reference Include="System.Runtime.WindowsRuntime">
      <HintPath>../../Player.App/System.Runtime.WindowsRuntime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>